---
- name: Evaluate {{ es_namespace }} namespace if not exists 
  k8s:
    api_version: v1
    kind: Namespace
    name: '{{ es_namespace }}'
    state: present

- name: Enable anyuid on Namespace user{{ item }}
  shell: "oc adm policy add-scc-to-user anyuid -z default -n {{ es_namespace }}"

- name: Provision ElasticSearch
  k8s:
    state: present
    resource_definition: "{{ lookup('template', 'elasticsearch.yaml.j2') }}"
